// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkigofnhssnngpoplaiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRraWdvZm5oc3Nubmdwb3BsYWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzgzMjMsImV4cCI6MjA3MTU1NDMyM30.Kd8P1MjAeNHa5OuYeZmxjjZTfw0Ls2fL7FvQM33XAe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});